-- Run this in the Supabase SQL editor for your project.
-- Creates the table that stores every student's exam result.

create table if not exists public.exam_results (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  student_name text not null,
  exam_id text not null,
  score integer not null,
  total integer not null,
  percentage integer not null,
  time_taken_seconds integer not null,
  answers jsonb not null default '{}'::jsonb,
  flagged_question_ids jsonb not null default '[]'::jsonb
);

-- Allow anonymous inserts (students saving results) and reads (teacher review).
alter table public.exam_results enable row level security;

create policy "Anyone can insert exam results"
  on public.exam_results
  for insert
  with check (true);

create policy "Anyone can read exam results"
  on public.exam_results
  for select
  using (true);
