export const TIK_QUEST_META = {
  game_title: "Detective Bity's TIK Quest",
  grade_level: 3,
  total_levels: 9,
  max_score: 900,
  player: 'Detective Bity',
  story_lines: [
    'Halo, Detektif Cilik! Aku Bity, detektif TIK kelas tiga. 🕵️',
    'Koper misterius berisi 9 kasus TIK menantimu untuk dipecahkan.',
    'Setiap kasus yang selesai memberimu 1 Lencana TIK yang berkilau.',
    'Kumpulkan semua 9 lencana untuk menjadi Master TIK Detective dan terima sertifikat kehormatanmu!',
  ],
}

export const TIK_LEVELS = [
  {
    id: 1,
    title: 'Kasus Urutan Pagi Hari',
    topic: 'Algoritma & Urutan',
    icon: '🧦',
    badge: 'Lencana Langkah Logis',
    badgeIcon: '🪜',
    color: {
      grad: 'from-sky-500 to-blue-700',
      chip: 'bg-sky-500',
      text: 'text-sky-600',
      ring: 'ring-sky-400',
      soft: 'bg-sky-50',
    },
    instruction: 'Susun urutan langkah yang logis sebelum berangkat sekolah. Seret kartu ke slot 1, 2, dan 3.',
    hint: 'Kaus kaki dipakai paling dulu, lalu sepatu, dan tali sepatu diikat paling akhir!',
    type: 'sequence',
    sequence: {
      slots: 3,
      items: [
        { id: 'sock', label: 'Memakai kaus kaki', icon: '🧦' },
        { id: 'shoe', label: 'Memakai sepatu', icon: '👟' },
        { id: 'lace', label: 'Mengikat tali sepatu', icon: '🪢' },
      ],
      correct: ['sock', 'shoe', 'lace'],
      spots: [
        { reason: 'Kaus kaki dipakai paling dulu supaya kaki hangat, bersih, dan nyaman sebelum masuk sepatu.' },
        { reason: 'Setelah kaki memakai kaus kaki, barulah sepatu dikenakan untuk melindungi kaki.' },
        { reason: 'Paling akhir, tali sepatu diikat supaya sepatu tidak longgar saat berjalan.' },
      ],
      success: 'Urutan pagi hari benar! Kamu siap berangkat sekolah!',
    },
  },
  {
    id: 2,
    title: 'Kasus Kamar Berantakan',
    topic: 'Dekomposisi',
    icon: '🧹',
    badge: 'Lencana Pemecah Tugas',
    badgeIcon: '🧩',
    color: {
      grad: 'from-emerald-500 to-teal-700',
      chip: 'bg-emerald-500',
      text: 'text-emerald-600',
      ring: 'ring-emerald-400',
      soft: 'bg-emerald-50',
    },
    instruction: 'Pecahkan tujuan besar menjadi tugas-tugas kecil. Seret tugas yang benar ke kotak tujuan, dan buang yang salah!',
    hint: 'Yang membantu membereskan kamar: merapikan tempat tidur, menyapu lantai, merapikan meja belajar. Menonton TV tidak!',
    type: 'decompose',
    decompose: {
      goalLabel: 'Tujuan Besar: Membersihkan Kamar',
      correct: [
        { id: 'bed', label: 'Merapikan tempat tidur', icon: '🛏️' },
        { id: 'sweep', label: 'Menyapu lantai', icon: '🧹' },
        { id: 'table', label: 'Merapikan meja belajar', icon: '📚' },
      ],
      distractors: [
        { id: 'tv', label: 'Menonton TV', icon: '📺' },
        { id: 'toys', label: 'Meninggalkan mainan di lantai', icon: '🧸' },
      ],
      teach: 'Tugas kecil yang membantu "Membersihkan Kamar": merapikan tempat tidur, menyapu lantai, dan merapikan meja belajar. Menonton TV dan membiarkan mainan bertumpuk bukan bagian dari rencana!',
      success: 'Tugas besar terpecah menjadi langkah kecil! Kamar bersih!',
    },
  },
  {
    id: 3,
    title: 'Kasus Kode Rahasia',
    topic: 'Pengenalan Pola',
    icon: '🔢',
    badge: 'Lencana Pembaca Pola',
    badgeIcon: '✨',
    color: {
      grad: 'from-violet-500 to-purple-700',
      chip: 'bg-violet-500',
      text: 'text-violet-600',
      ring: 'ring-violet-400',
      soft: 'bg-violet-50',
    },
    instruction: 'Pecahkan kode rahasia! Isi pola yang kosong supaya kode yang tersembunyi terbuka.',
    hint: 'Perhatikan urutan yang berulang: bintang kemudian lingkaran. Angka bergantian 2 dan 4. Terus apa yang berikutnya?',
    type: 'patterns',
    patterns: {
      solves: [
        {
          id: 'visual',
          display: ['⭐', '⭕', '⭐', '⭕', '?'],
          options: [
            { id: 'tri', label: 'Segitiga', icon: '🔺' },
            { id: 'star', label: 'Bintang', icon: '⭐' },
            { id: 'circ', label: 'Lingkaran', icon: '⭕' },
          ],
          answer: 'star',
          hint: 'Pola bintang dan lingkaran bergantian. Setelah lingkaran, giliran siapa?',
          teach: 'Coba lihat polanya: bintang → lingkaran → bintang → lingkaran. Karena selalu bergantian, setelah lingkaran giliran Bintang (⭐)!',
          success: 'Pola bintang terbaca!',
        },
        {
          id: 'number',
          display: ['2', '4', '2', '4', '?'],
          options: [
            { id: 'n2', label: '2', icon: '2️⃣' },
            { id: 'n4', label: '4', icon: '4️⃣' },
            { id: 'n6', label: '6', icon: '6️⃣' },
          ],
          answer: 'n2',
          hint: 'Angka berulang 2, 4, 2, 4. Setelah 4, angka apa lagi?',
          teach: 'Lihat urutannya: 2 → 4 → 2 → 4. Angkanya selalu bergantian, jadi setelah 4 giliran 2 lagi!',
          success: 'Pola angka terbaca!',
        },
      ],
      success: 'Kode rahasia terbuka! Posisi pola teridentifikasi!',
    },
  },
  {
    id: 4,
    title: 'Kasus Anatomi Komputer',
    topic: 'Perangkat Komputer & Manfaatnya',
    icon: '🖥️',
    badge: 'Lencana Ahli Perangkat',
    badgeIcon: '🖥️',
    color: {
      grad: 'from-amber-400 to-orange-600',
      chip: 'bg-amber-500',
      text: 'text-amber-600',
      ring: 'ring-amber-400',
      soft: 'bg-amber-50',
    },
    instruction: 'Hubungkan setiap perangkat komputer dengan fungsinya! Lalu pilih penggunaan komputer yang positif.',
    hint: 'Monitor untuk melihat gambar, keyboard untuk mengetik, mouse untuk mengeklik hal di layar.',
    type: 'machine',
    machine: {
      pairs: [
        {
          left: { id: 'monitor', icon: '🖥️', label: 'Monitor' },
          right: { id: 'f-monitor', icon: '🖼️', label: 'Menampilkan gambar di layar' },
          teach: 'Monitor adalah layar besar tempat kamu melihat gambar dan video.',
        },
        {
          left: { id: 'keyboard', icon: '⌨️', label: 'Keyboard' },
          right: { id: 'f-keyboard', icon: '🔤', label: 'Mengetik huruf dan angka' },
          teach: 'Keyboard memiliki huruf dan angka untuk diketik.',
        },
        {
          left: { id: 'mouse', icon: '🖱️', label: 'Mouse' },
          right: { id: 'f-mouse', icon: '👆', label: 'Mengklik ikon di layar' },
          teach: 'Mouse dipakai untuk mengarahkan dan mengeklik ikon di layar.',
        },
      ],
      bonus: {
        prompt: 'Bonus Kecerdasan Digital: pilih penggunaan komputer yang positif!',
        good: { id: 'good', icon: '📚', label: 'Belajar dan mengetik tugas sekolah' },
        bad: { id: 'bad', icon: '🎮', label: 'Main game seharian tanpa istirahat' },
        teach: 'Penggunaan komputer yang positif adalah untuk belajar dan mengerjakan tugas. Bermain game seharian tanpa istirahat tidak baik untuk kesehatan!',
        success: 'Komputer adalah teman belajar yang hebat!',
      },
    },
  },
  {
    id: 5,
    title: 'Kasus Pesan Ramah',
    topic: 'Aplikasi Penyampai Pesan',
    icon: '💬',
    badge: 'Lencana Teman Santun',
    badgeIcon: '💬',
    color: {
      grad: 'from-rose-500 to-pink-700',
      chip: 'bg-rose-500',
      text: 'text-rose-600',
      ring: 'ring-rose-400',
      soft: 'bg-rose-50',
    },
    instruction: 'Bantu Bity membalas pesan dengan sopan dan aman di aplikasi chat!',
    hint: 'Gunakan kata "mohon" dan "terima kasih". Jangan mengetik dengan huruf besar semua dan kasar.',
    type: 'chat',
    chat: {
      appName: 'Bity Chat',
      chats: [
        {
          from: 'Ibu Guru',
          avatar: '👩‍🏫',
          message: 'Halo! Ada yang ingin ditanyakan tentang tugas TIK?',
          options: [
            {
              id: 'a',
              text: 'Halo Ibu Guru, mohon maaf mengganggu, mau bertanya tugas TIK.',
              correct: true,
              reply: 'Wah, sangat santun sekali! Silakan bertanya ya. 😊',
            },
            {
              id: 'b',
              text: 'HOI KIRIM TUGAS DONG!',
              correct: false,
              reply: 'Hmm, ayo kita bicara dengan sopan ya. 🙏',
            },
          ],
          warning: 'Pesan yang sopan diawali dengan salam dan memakai kata yang halus. Jangan mengetik dengan huruf besar semua atau nada memerintah!',
        },
        {
          from: 'Teman Sekelas',
          avatar: '🧒',
          message: 'Boleh pinjam pensil warnamu?',
          options: [
            {
              id: 'c',
              text: 'Boleh kok, ini pensilnya. Semangat ya!',
              correct: true,
              reply: 'Makasih banyak! Kamu teman yang baik. 💙',
            },
            {
              id: 'd',
              text: 'TIDAK! JANGAN SENTUH!',
              correct: false,
              reply: 'Waduh, ayo bicara baik-baik ya. 🙈',
            },
          ],
          warning: 'Balas teman dengan ramah dan mau berbagi. Kata "boleh kok" dan "makasih" membuat teman merasa dihargai.',
        },
      ],
      success: 'Semua pesanmu sopan dan aman!',
    },
  },
  {
    id: 6,
    title: 'Kasus Studio Seni Digital',
    topic: 'Program Pengolah Gambar',
    icon: '🎨',
    badge: 'Lencana Pelukis Digital',
    badgeIcon: '🎨',
    color: {
      grad: 'from-teal-400 to-cyan-600',
      chip: 'bg-teal-500',
      text: 'text-teal-600',
      ring: 'ring-teal-400',
      soft: 'bg-teal-50',
    },
    instruction: 'Pasangkan setiap alat gambar dengan kegunaannya, lalu saksikan gambarmu berubah!',
    hint: 'Ember mengisi warna luas, penghapus membersihkan, pensil menggambar garis, bentuk menambah lingkaran dan bintang.',
    type: 'studio',
    studio: {
      pairs: [
        {
          tool: { id: 'bucket', icon: '🪣', label: 'Ember Cat (Fill)' },
          action: { id: 'a-bucket', label: 'Mewarnai area yang luas', icon: '🌞' },
          teach: 'Ember Cat (Fill) mengisi warna ke area yang besar, seperti langit, rumput, atau matahari.',
        },
        {
          tool: { id: 'eraser', icon: '🧽', label: 'Penghapus (Eraser)' },
          action: { id: 'a-eraser', label: 'Memperbaiki gambar yang salah', icon: '🧽' },
          teach: 'Penghapus (Eraser) membersihkan bagian gambar yang salah atau noda.',
        },
        {
          tool: { id: 'pencil', icon: '✏️', label: 'Pensil (Pencil)' },
          action: { id: 'a-pencil', label: 'Menggambar garis bebas', icon: '✏️' },
          teach: 'Pensil (Pencil) untuk menggambar garis bebas seperti sketsa.',
        },
        {
          tool: { id: 'shapes', icon: '🔷', label: 'Bentuk (Shapes)' },
          action: { id: 'a-shapes', label: 'Menambah lingkaran dan bintang', icon: '⭐' },
          teach: 'Bentuk (Shapes) menambah lingkaran, bintang, dan bentuk-bentuk lainnya.',
        },
      ],
      success: 'Karya seni digitalmu sempurna!',
    },
  },
  {
    id: 7,
    title: 'Kasus Dokumen yang Benar',
    topic: 'Program Pengolah Kata',
    icon: '🗂️',
    badge: 'Lencana Dokumen Cermat',
    badgeIcon: '📄',
    color: {
      grad: 'from-cyan-400 to-sky-600',
      chip: 'bg-cyan-500',
      text: 'text-cyan-600',
      ring: 'ring-cyan-400',
      soft: 'bg-cyan-50',
    },
    instruction: 'Ikuti 3 langkah cepat: perbesar huruf, simpan berkas, lalu cetak dokumen!',
    hint: 'Huruf kecil susah dibaca, jadi perbesar dulu. Jangan lupa simpan supaya tidak hilang, lalu cetak.',
    type: 'office',
    office: {
      paper: {
        title: 'Kisah Kucing Tini',
        body: 'Tini adalah kucing yang suka berlari di taman. Setiap pagi ia mengejar kupu-kupu dan bermain dengan daun kering. Tini senang sekali hidup di rumah yang hangat.',
      },
      tasks: [
        {
          id: 'font',
          icon: '🔠',
          label: 'Perbesar huruf',
          whisper: 'Huruf terlalu kecil. Perbesar supaya enak dibaca!',
          done: 'Huruf besar dan mudah dibaca!',
        },
        {
          id: 'save',
          icon: '💾',
          label: 'Simpan berkas (disket)',
          whisper: 'Ceritamu bisa hilang lho! Simpan dulu ya.',
          done: 'Berkas tersimpan! Disket aman!',
        },
        {
          id: 'print',
          icon: '🖨️',
          label: 'Cetak ke kertas',
          whisper: 'Sekarang hasilkan cerita di atas kertas!',
          done: 'Dokumen keluar dari printer!',
        },
      ],
      success: 'Dokumen rapih, tersimpan, dan tercetak!',
    },
  },
  {
    id: 8,
    title: 'Kasus Presentasi Cemerlang',
    topic: 'Program Presentasi / Slide',
    icon: '📽️',
    badge: 'Lencana Master Presentasi',
    badgeIcon: '📽️',
    color: {
      grad: 'from-indigo-400 to-blue-600',
      chip: 'bg-indigo-500',
      text: 'text-indigo-600',
      ring: 'ring-indigo-400',
      soft: 'bg-indigo-50',
    },
    instruction: 'Rangkai slide presentasi yang jelas: teks ringkas dan warna yang mudah dibaca!',
    hint: 'Slide yang baik memakai kalimat singkat bukan paragraf panjang, dan teks gelap di atas latar terang.',
    type: 'slides',
    slides: {
      tasks: [
        {
          id: 'text',
          label: 'Pilih isi slide yang tepat',
          options: [
            { id: 'concise', icon: '☀️', label: '"Hari Ini Cerah" — ringkas dan jelas', correct: true },
            { id: 'long', icon: '📄', label: 'Paragraf panjang dan berdesakan tanpa jeda', correct: false },
          ],
          teach: 'Slide yang baik memakai kalimat ringkas dan jelas, bukan paragraf panjang yang susah dibaca.',
          success: 'Teks ringkas yang mudah dibaca!',
        },
        {
          id: 'scheme',
          label: 'Pilih kombinasi warna yang jelas',
          options: [
            { id: 'good', icon: '⚫', label: 'Teks gelap di atas latar terang', correct: true },
            { id: 'bad', icon: '🟡', label: 'Teks kuning di atas kertas putih', correct: false },
          ],
          teach: 'Kombinasi paling mudah dibaca adalah teks gelap di atas latar terang. Teks kuning di atas putih terlalu samar!',
          success: 'Kontras tinggi, semua orang bisa membaca!',
        },
      ],
      success: 'Slide presentasimu cemerlang!',
    },
  },
  {
    id: 9,
    title: 'Kasus Posisi Sehat',
    topic: 'Aturan & K3 TIK',
    icon: '🦴',
    badge: 'Lencana Tubuh Sehat',
    badgeIcon: '💪',
    color: {
      grad: 'from-orange-400 to-red-600',
      chip: 'bg-orange-500',
      text: 'text-orange-600',
      ring: 'ring-orange-400',
      soft: 'bg-orange-50',
    },
    instruction: 'Jaga kesehatan tubuh saat di depan komputer: duduk tegak, atur layar, dan istirahatkan mata!',
    hint: 'Punggung tegak 90°, layar cukup terang tapi tidak menyilaukan, dan mata perlu istirahat 20 detik.',
    type: 'ergo',
    ergo: {
      posture: { target: 90, tolerance: 10 },
      brightness: { min: 1, max: 10, lo: 4, hi: 8 },
      breakSeconds: 20,
      success: 'Postur sehat! Mata dan punggungmu berterima kasih!',
    },
  },
]